// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/inventory/infrastructure/grpc/proto/inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_internal_inventory_infrastructure_grpc_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_infrastructure_grpc_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	mi := &file_internal_inventory_infrastructure_grpc_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_infrastructure_grpc_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockRequest.ProtoReflect.Descriptor instead.
func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CheckStockRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockResponse) Reset() {
	*x = CheckStockResponse{}
	mi := &file_internal_inventory_infrastructure_grpc_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse) ProtoMessage() {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_infrastructure_grpc_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResponse.ProtoReflect.Descriptor instead.
func (*CheckStockResponse) Descriptor() ([]byte, []int) {
	return file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *CheckStockResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_internal_inventory_infrastructure_grpc_proto_inventory_proto protoreflect.FileDescriptor

const file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"<internal/inventory/infrastructure/grpc/proto/inventory.proto\x12\tinventory\"4\n" +
	"\x04Item\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\":\n" +
	"\x11CheckStockRequest\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.inventory.ItemR\x05items\"2\n" +
	"\x12CheckStockResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable2]\n" +
	"\x10InventoryService\x12I\n" +
	"\n" +
	"CheckStock\x12\x1c.inventory.CheckStockRequest\x1a\x1d.inventory.CheckStockResponseBbZ`github.com/dmehra2102/Order-Management-System/internal/inventory/infrastructure/grpc/proto;protob\x06proto3"

var (
	file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDescOnce sync.Once
	file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDescData []byte
)

func file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDescGZIP() []byte {
	file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDescOnce.Do(func() {
		file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDesc), len(file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDesc)))
	})
	return file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDescData
}

var file_internal_inventory_infrastructure_grpc_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_inventory_infrastructure_grpc_proto_inventory_proto_goTypes = []any{
	(*Item)(nil),               // 0: inventory.Item
	(*CheckStockRequest)(nil),  // 1: inventory.CheckStockRequest
	(*CheckStockResponse)(nil), // 2: inventory.CheckStockResponse
}
var file_internal_inventory_infrastructure_grpc_proto_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.CheckStockRequest.items:type_name -> inventory.Item
	1, // 1: inventory.InventoryService.CheckStock:input_type -> inventory.CheckStockRequest
	2, // 2: inventory.InventoryService.CheckStock:output_type -> inventory.CheckStockResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_inventory_infrastructure_grpc_proto_inventory_proto_init() }
func file_internal_inventory_infrastructure_grpc_proto_inventory_proto_init() {
	if File_internal_inventory_infrastructure_grpc_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDesc), len(file_internal_inventory_infrastructure_grpc_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_inventory_infrastructure_grpc_proto_inventory_proto_goTypes,
		DependencyIndexes: file_internal_inventory_infrastructure_grpc_proto_inventory_proto_depIdxs,
		MessageInfos:      file_internal_inventory_infrastructure_grpc_proto_inventory_proto_msgTypes,
	}.Build()
	File_internal_inventory_infrastructure_grpc_proto_inventory_proto = out.File
	file_internal_inventory_infrastructure_grpc_proto_inventory_proto_goTypes = nil
	file_internal_inventory_infrastructure_grpc_proto_inventory_proto_depIdxs = nil
}
